baseURL: "https://ribbit.anyfrog.net/"
languageCode: 'ja'
title: "*ribbit*"
theme: PaperMod

hasCJKLanguage: true
summaryLength: 300

params:
  disableSpecial1stPost: true
  socialIcons:
  - name: "twitter"
    url: "https://twitter.com/kznrluk"
